#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           40
bspc config active_border_color  "#282828"
bspc config focused_border_color  "#282828" 
bspc config active_border_color  "#282828" 
bspc config normal_border_color  "#282828" 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# bspc config border_radius        40

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

compton -b --config ~/.config/compton/config

setxkbmap "us,ru" ",winkeys" "grp:alt_shift_toggle"

~/.config/polybar/launch.sh

feh --bg-scale ~/foggy.jpg
